LW-003
WojciechBarwinski/legendary-warehouse pull request #2
Opened 2024-06-26 13:21 UTC by WojciechBarwinski

Dodano Dockerfile oraz ustawiono bazowy port aplikacji na 8081

2024-06-29 14:57 UTC, gestru requested changes

2024-06-29 14:57 UTC, gestru commented on Dockerfile
> +#mvn clean package    <---- do zbudowania aplikacji po zmianach
zamień na angielski - nie chcemy mieć w repo polskich komentarzy czy nazw

2024-06-29 14:58 UTC, gestru commented on Dockerfile
> +#mvn clean package    <---- do zbudowania aplikacji po zmianach
I przerzuć te komendy do osobnego pliku albo readme

2024-07-01 09:03 UTC, WojciechBarwinski commented on Dockerfile
> +#mvn clean package    <---- do zbudowania aplikacji po zmianach
przerzucone do osobnego pliku który dodałem do gitignora

2024-07-01 18:09 UTC, gestru approved these changes

2024-07-01 18:17 UTC, merged